version: 2
jobs:
  abas:
    docker:
      - image: python:3.8

    steps:
    - checkout
    - run: ls && sleep 1s
    - run: date && sleep 3s
    - run: date && sleep 2s
    - run: ls && sleep 2s
    - run: date && sleep 2s


workflows:
  version: 2
  abas:
    jobs:
    - abas
