version: 2
jobs:
  abas:
    docker:
      - image: python:3.8

    steps:
    - checkout
    - run: ls
    - run: date && sleep 3s
    - run: date
    - run: ls
    - run: date


workflows:
  version: 2
  abas:
    jobs:
    - abas
